apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DEBUG: "False"
  ALLOWED_HOSTS: "[]"

---
#
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: redis-config
#data:
#  PORT: 6379