apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: django-app
          image: django-app-image
          ports:
            - containerPort: 8000
              name: django
          envFrom:
          - configMapRef:
              name: django-config
          env:
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django-secrets
                  key: SECRET_KEY
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_HOST
              value: redis-service
#            - name: ALLOWED_HOSTS
#                valueFrom:
#                  configMapKeyRef:
#                    name: django-config
#                    key: ALLOWED_HOSTS