apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres

spec:
#  type: ClusterIP
#  selector:
#    app: postgres
#  ports:
#    - port: 5432
#      targetPort: 5432
  ports:
    - port: 5432
      name: postgres
  type: NodePort
  selector:
    app: postgres