apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 1
  template:
    spec:
      volumes:
        - name: local-django-volume-mount
          persistentVolumeClaim:
            claimName: django-local-claim
      containers:
        - name: django-app
          image: django-app-image
          ports:
            - containerPort: 8000
              name: django
            - containerPort: 22
              name: ssh
          volumeMounts:
            - name: local-django-volume-mount
              mountPath: /app  # in the container filesystem

---

kind: Service
apiVersion: v1
metadata:
  name: django
spec:
  type: NodePort
  selector:
    app: django
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    name: django
  - protocol: TCP
    port: 2222
    targetPort: 22
    name: ssh