kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: django-local-claim
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi
  volumeName: django-local-pv