apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
#  annotations:
#    volume.beta.kubernetes.io/mount-options: "dir_mode=0777,file_mode=0777,uid=1000,gid=1000"
spec:
  resources:
    requests:
      storage: 250Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 250Mi
  hostPath:
    path: /data/ # Minikube folder
